# Generated by Django 2.0.7 on 2019-10-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='drinks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
